"""initial schema

Revision ID: a848ec0d81f5
Revises: 
Create Date: 2026-05-31 10:31:35.664362
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a848ec0d81f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _set_fk_checks(enabled: bool) -> None:
    # The schema has a circular FK (teams.captain_id ↔ players.team_id) and the
    # autogenerated create order references tables before they exist. MySQL/TiDB
    # enforce FKs at CREATE time, so defer checks during the initial migration.
    # No-op on SQLite (which doesn't enforce this here).
    bind = op.get_bind()
    if bind.dialect.name == "mysql":
        op.execute(f"SET FOREIGN_KEY_CHECKS={1 if enabled else 0}")


def upgrade() -> None:
    _set_fk_checks(False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('batting_style', sa.Enum('RIGHT_HAND', 'LEFT_HAND', name='battingstyle'), nullable=False),
    sa.Column('bowling_style', sa.Enum('NONE', 'FAST', 'MEDIUM', 'OFF_SPIN', 'LEG_SPIN', 'LEFT_ARM_SPIN', 'LEFT_ARM_FAST', name='bowlingstyle'), nullable=False),
    sa.Column('role', sa.Enum('BATSMAN', 'BOWLER', 'ALL_ROUNDER', 'WICKET_KEEPER', name='playerrole'), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('coach', sa.String(length=120), nullable=True),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('PUBLIC', 'MATCH_ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('format', sa.Enum('LEAGUE', 'KNOCKOUT', 'ROUND_ROBIN', 'GROUP_STAGE', name='tournamentformat'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'ONGOING', 'COMPLETED', 'REJECTED', name='tournamentstatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_name'), ['name'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=32), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('overs_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'LIVE', 'INNINGS_BREAK', 'COMPLETED', 'ABANDONED', name='matchstatus'), nullable=False),
    sa.Column('toss_winner_id', sa.Integer(), nullable=True),
    sa.Column('toss_decision', sa.Enum('BAT', 'BOWL', name='tossdecision'), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('result_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('tournament_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('tied', sa.Integer(), nullable=False),
    sa.Column('no_result', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('net_run_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'team_id', name='uq_tournament_team')
    )
    with op.batch_alter_table('tournament_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_teams_tournament_id'), ['tournament_id'], unique=False)

    op.create_table('innings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.Column('batting_team_id', sa.Integer(), nullable=False),
    sa.Column('bowling_team_id', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('total_wickets', sa.Integer(), nullable=False),
    sa.Column('legal_balls', sa.Integer(), nullable=False),
    sa.Column('extras_wide', sa.Integer(), nullable=False),
    sa.Column('extras_no_ball', sa.Integer(), nullable=False),
    sa.Column('extras_bye', sa.Integer(), nullable=False),
    sa.Column('extras_leg_bye', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batting_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bowling_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'innings_number', name='uq_match_innings')
    )
    with op.batch_alter_table('innings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_innings_match_id'), ['match_id'], unique=False)

    op.create_table('match_admins',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'user_id')
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=False),
    sa.Column('balls_faced', sa.Integer(), nullable=False),
    sa.Column('fours', sa.Integer(), nullable=False),
    sa.Column('sixes', sa.Integer(), nullable=False),
    sa.Column('is_out', sa.Boolean(), nullable=False),
    sa.Column('legal_balls_bowled', sa.Integer(), nullable=False),
    sa.Column('runs_conceded', sa.Integer(), nullable=False),
    sa.Column('wickets', sa.Integer(), nullable=False),
    sa.Column('catches', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_match_player_stats')
    )
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_stats_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_player_id'), ['player_id'], unique=False)

    op.create_table('balls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('innings_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('ball_in_over', sa.Integer(), nullable=False),
    sa.Column('striker_id', sa.Integer(), nullable=False),
    sa.Column('non_striker_id', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('runs_batsman', sa.Integer(), nullable=False),
    sa.Column('extra_type', sa.Enum('NONE', 'WIDE', 'NO_BALL', 'BYE', 'LEG_BYE', name='extratype'), nullable=False),
    sa.Column('extra_runs', sa.Integer(), nullable=False),
    sa.Column('is_wicket', sa.Boolean(), nullable=False),
    sa.Column('wicket_type', sa.Enum('NONE', 'BOWLED', 'CAUGHT', 'LBW', 'RUN_OUT', 'STUMPED', 'HIT_WICKET', 'RETIRED_HURT', name='wickettype'), nullable=False),
    sa.Column('dismissed_player_id', sa.Integer(), nullable=True),
    sa.Column('fielder_id', sa.Integer(), nullable=True),
    sa.Column('is_legal_delivery', sa.Boolean(), nullable=False),
    sa.Column('commentary', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dismissed_player_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fielder_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['non_striker_id'], ['players.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['striker_id'], ['players.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('balls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balls_innings_id'), ['innings_id'], unique=False)

    # ### end Alembic commands ###
    _set_fk_checks(True)


def downgrade() -> None:
    _set_fk_checks(False)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_balls_innings_id'))

    op.drop_table('balls')
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_stats_match_id'))

    op.drop_table('player_match_stats')
    op.drop_table('match_admins')
    with op.batch_alter_table('innings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_innings_match_id'))

    op.drop_table('innings')
    with op.batch_alter_table('tournament_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_teams_tournament_id'))

    op.drop_table('tournament_teams')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_tournament_id'))
        batch_op.drop_index(batch_op.f('ix_matches_status'))

    op.drop_table('matches')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_name'))

    op.drop_table('tournaments')
    op.drop_table('venues')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))

    op.drop_table('teams')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))

    op.drop_table('players')
    # ### end Alembic commands ###
    _set_fk_checks(True)
